Test non-default repo

diff --git a/.github/workflows/pr-open.yml b/.github/workflows/pr-open.yml
--- a/.github/workflows/pr-open.yml
+++ b/.github/workflows/pr-open.yml
@@ -33,6 +33,36 @@ jobs:
             exit 1
           fi
 
+
+  repository:
+    name: Test Non-Default Repository
+    runs-on: ubuntu-24.04
+    steps:
+      - uses: actions/checkout@v4
+      - id: repository
+        uses: ./
+        with:
+          commands: |
+            git remote -v
+            if ! git remote -v | grep -q "bcgov/openshift-quickstart"; then
+              echo "Error! Repository bcgov/openshift-quickstart is not checked out."
+              exit 1
+            fi
+          oc_namespace: ${{ vars.oc_namespace }}
+          oc_server: ${{ vars.oc_server }}
+          oc_token: ${{ secrets.oc_token }}
+          repository: bcgov/openshift-quickstart
+          ref: main
+          timeout: 1m
+
+      - run: |
+          # Verify outputs
+          echo "Outputs: ${{ toJSON(steps.repository.outputs) }}"
+          if [ "${{ steps.repository.outputs.triggered }}" != "true" ]; then
+            echo "Error!  Verify outputs."
+            exit 1
+          fi
+
   legacy:
     name: Test Legacy Binary
     runs-on: ubuntu-24.04
@@ -76,7 +106,7 @@ jobs:
 
   results:
     name: PR Results
-    needs: [whoami, legacy, cronjob]
+    needs: [whoami, repository, legacy, cronjob]
     if: always()
     runs-on: ubuntu-24.04
     steps:
