Test exit 1

diff --git a/.github/workflows/pr-open.yml b/.github/workflows/pr-open.yml
--- a/.github/workflows/pr-open.yml
+++ b/.github/workflows/pr-open.yml
@@ -40,7 +40,11 @@ jobs:
             echo "Error! Generic commands output did not match expected value."
             exit 1
           fi
-
+          
+        - run: |
+          # Test failure
+          echo "Fail!"
+          exit 1
 
   repository:
     name: Test Non-Default Repository
