Test forced skip

diff --git a/.github/workflows/pr-open.yml b/.github/workflows/pr-open.yml
--- a/.github/workflows/pr-open.yml
+++ b/.github/workflows/pr-open.yml
@@ -10,8 +10,18 @@ concurrency:
 permissions: {}
 
 jobs:
+  junk:
+    name: Junk
+    runs-on: ubuntu-22.04
+    steps:    
+      - run: |
+          # Test failure
+          echo "Fail!"
+          exit 1
+
   whoami:
     name: Test Command
+    needs: [junk]
     runs-on: ubuntu-24.04
     steps:
       - uses: actions/checkout@v6
@@ -40,11 +50,6 @@ jobs:
             echo "Error! Generic commands output did not match expected value."
             exit 1
           fi
-          
-      - run: |
-          # Test failure
-          echo "Fail!"
-          exit 1
 
   repository:
     name: Test Non-Default Repository
