feat: follow cronjobs, improve handling (#28)

diff --git a/.github/workflows/pr-open.yml b/.github/workflows/pr-open.yml
--- a/.github/workflows/pr-open.yml
+++ b/.github/workflows/pr-open.yml
@@ -22,12 +22,11 @@ jobs:
           oc_namespace: ${{ vars.oc_namespace }}
           oc_server: ${{ vars.oc_server }}
           oc_token: ${{ secrets.oc_token }}
+          timeout: 1m
 
-      - env:
-          outputs: ${{ toJSON(steps.whoami.outputs) }}
-        run: |
+      - run: |
           # Verify outputs
-          echo "Outputs: ${{ env.outputs }}"
+          echo "Outputs: ${{ toJSON(steps.whoami.outputs) }}"
           if [ "${{ steps.whoami.outputs.triggered }}" != "true" ]; then
             echo "Error!  Verify outputs."
             exit 1
@@ -45,6 +44,7 @@ jobs:
           oc_server: ${{ vars.oc_server }}
           oc_token: ${{ secrets.oc_token }}
           oc_version: '4.1'
+          timeout: 1m
           triggers: ('action.yml')
 
   cronjob:
@@ -59,17 +59,28 @@ jobs:
           oc_namespace: ${{ vars.oc_namespace }}
           oc_server: ${{ vars.oc_server }}
           oc_token: ${{ secrets.oc_token }}
+          overwrite: true
           parameters: -p ZONE=${{ github.event.number }}
           triggers: ('.github/' 'action.yml' 'cronjob/')
       
-      - uses: ./
+      - id: cronjob
+        uses: ./
         with:
           cronjob: ${{ github.event.repository.name }}-${{ github.event.number }}-cronjob
           cronjob_tail: -1
           oc_namespace: ${{ vars.oc_namespace }}
           oc_server: ${{ vars.oc_server }}
           oc_token: ${{ secrets.oc_token }}
+          timeout: 1m
           triggers: ('.github/' 'action.yml' 'cronjob/')
+
+      - run: |
+          # Verify outputs
+          echo "Outputs: ${{ toJSON(steps.cronjob.outputs) }}"
+          if [ "${{ steps.cronjob.outputs.job-name }}" == "" ]; then
+            echo "Error!  Verify outputs."
+            exit 1
+          fi
 
   results:
     name: PR Results
diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -18,23 +18,19 @@ inputs:
     description: OpenShift access token
     required: true
     minLength: 32
-  triggers:
-    description: Paths used to trigger this action; e.g. ('./backend/' './frontend/)
 
   ### Typical / recommended
   commands:
     description: Command to run, generally oc commands; e.g. oc whoami
   cronjob:
     description: Cronjob to run, watch and report on
+  triggers:
+    description: Bash array to diff for triggering, omit to always run; e.g. ('./backend/' './frontend/)
 
   ### Usually a bad idea / not recommended
   cronjob_tail:
     description: Number of cronjob log lines to tail; use -1 for all
-    default: 0
-  cronjob_timeout:
-    description: Timeout for cronjob to run; e.g. 5m
-    default: 5m
-    pattern: '^[0-9]+[mhs]$'
+    default: -1
   diff_branch:
     description: Branch to diff against
     default: ${{ github.event.repository.default_branch }}
@@ -45,8 +41,15 @@ inputs:
   repository:
     description: Optionally, specify a different repo to clone
     default: ${{ github.repository }}
+  timeout:
+    description: Timeout for commands or cronjob; e.g. 10m
+    default: 10m
+    pattern: '^[0-9]+[mhs]$'
 
 outputs:
+  job-name:
+    description: Name of the job created from the cronjob param
+    value: ${{ steps.cronjob.outputs.job-name }}
   triggered:
     description: Whether the action was triggered
     value: ${{ steps.diff.outputs.triggered }}
@@ -102,25 +105,28 @@ runs:
         ${{ inputs.commands }}
 
     - if: steps.diff.outputs.triggered == 'true' && inputs.cronjob
+      id: cronjob
       shell: bash
       run: |
+        # Cronjob => job
         JOB_NAME=${{ inputs.cronjob }}--$(date +"%Y-%m-%d--%H-%M-%S")
-        echo "JOB_NAME=${JOB_NAME}" >> $GITHUB_ENV
-
         oc create job ${JOB_NAME} --from=cronjob/${{ inputs.cronjob }}
-        oc wait --for jsonpath='{.status.phase}'=Succeeded pod --selector=job-name=${JOB_NAME} \
-           --timeout=${{ inputs.cronjob_timeout }}
-        echo "Job successful!"
 
-    # Provide logs if requested, even on fail
-    - if: always() && steps.diff.outputs.triggered == 'true' && inputs.cronjob
-      shell: bash
-      run: |
-        if [ "${{ inputs.cronjob_logs }}" != "false" ]; then
-          echo -e "\n\n--- Logs ---\n\n"
-          oc logs --tail=${{ inputs.cronjob_tail }} --selector=job-name=${JOB_NAME}
-          echo -e "\n\n---\n\n"
-        fi
+        # Wait for status=ready|completed - oc wait fails for overly quick jobs
+        timeout ${{ inputs.timeout }} bash -c "
+        while true; do
+          oc get pods -l job-name=${JOB_NAME} --no-headers | awk '{print $3}' | grep -qi 'running\|completed' && break
+          sleep 5
+        done" || { echo "Timeout waiting for job to start"; exit 1; }
+
+        # Follow logs
+        echo -e "\n\n--- Start logs for job ${JOB_NAME} ---"
+        oc logs -l job-name=${JOB_NAME} --follow --tail=${{ inputs.cronjob_tail }}
+        echo -e "--- End logs ---\n\n"
+
+        # Results
+        echo "job-name=${JOB_NAME}" >> $GITHUB_OUTPUT
+        echo "Job successful!"
 
     # Action repo needs to be present for cleanup/tests
     - if: steps.diff.outputs.triggered == 'true' && github.repository != inputs.repository
